macro_rules! app_invoke_handler {
    () => {
        tauri::generate_handler![
            crate::interfaces::commands::device_commands::cancel_transcription,
            crate::interfaces::commands::device_commands::get_queue_status,
            crate::interfaces::commands::device_commands::get_available_devices,
            crate::interfaces::commands::media_commands::select_media_files,
            crate::interfaces::commands::storage_commands::get_transcription_dir,
            crate::interfaces::commands::storage_commands::save_transcription,
            crate::interfaces::commands::storage_commands::load_transcription,
            crate::interfaces::commands::storage_commands::delete_transcription,
            crate::interfaces::commands::storage_commands::list_transcriptions,
            crate::interfaces::commands::storage_commands::get_storage_info,
            crate::interfaces::commands::storage_commands::get_storage_location,
            crate::interfaces::commands::storage_commands::set_storage_location,
            crate::interfaces::commands::storage_commands::validate_storage_location,
            crate::interfaces::commands::storage_commands::open_storage_location_command,
            crate::interfaces::commands::media_commands::export_transcription,
            crate::interfaces::commands::model_commands::get_models_dir_command,
            crate::interfaces::commands::model_commands::set_models_dir_command,
            crate::interfaces::commands::model_commands::open_models_folder_command,
            crate::interfaces::commands::app_commands::open_archive_folder_command,
            crate::interfaces::commands::app_commands::open_app_directory_command,
            crate::interfaces::commands::app_commands::set_close_behavior_command,
            crate::interfaces::commands::app_commands::get_close_behavior_command,
            crate::interfaces::commands::app_commands::has_active_work_now,
            crate::interfaces::commands::app_commands::quit_application_command,
            crate::interfaces::commands::model_commands::download_model,
            crate::interfaces::commands::model_commands::cancel_model_download,
            crate::interfaces::commands::model_commands::get_local_models,
            crate::interfaces::commands::model_commands::delete_model,
            crate::interfaces::commands::model_commands::clear_cache,
            crate::interfaces::commands::model_commands::get_disk_usage,
            crate::interfaces::commands::model_commands::save_selected_model,
            crate::interfaces::commands::model_commands::load_selected_model,
            crate::interfaces::commands::media_commands::get_files_metadata,
            crate::interfaces::commands::ffmpeg_commands::get_ffmpeg_status,
            crate::interfaces::commands::ffmpeg_commands::download_ffmpeg,
            crate::interfaces::commands::media_commands::read_file_as_base64,
            // Audio processing commands (Rust-native)
            crate::interfaces::commands::audio_commands::generate_waveform_peaks,
            crate::interfaces::commands::audio_commands::convert_audio_to_wav,
            crate::interfaces::commands::audio_commands::get_audio_duration,
            crate::interfaces::commands::audio_commands::extract_audio_segment,
            crate::interfaces::commands::audio_commands::get_audio_metadata,
            // Archive commands
            crate::interfaces::commands::media_commands::get_file_size,
            crate::interfaces::commands::media_commands::delete_file,
            crate::interfaces::commands::archive_commands::copy_file,
            crate::interfaces::commands::archive_commands::compress_media,
            crate::interfaces::commands::media_commands::convert_to_mp3,
            crate::interfaces::commands::archive_commands::get_archive_dir,
            // Phase 3: Rust Transcription commands
            crate::interfaces::commands::transcription_commands::init_transcription_manager,
            crate::interfaces::commands::transcription_commands::load_model_rust,
            crate::interfaces::commands::transcription_runtime_commands::transcribe_rust,
            crate::interfaces::commands::transcription_commands::unload_model_rust,
            crate::interfaces::commands::transcription_commands::is_model_loaded_rust,
            crate::interfaces::commands::transcription_commands::get_current_model_rust,
            // Native diarization commands
            crate::interfaces::commands::diarization_commands::diarize_native,
            crate::interfaces::commands::diarization_commands::diarize_sherpa,
            // Setup Wizard commands
            crate::interfaces::commands::setup_commands::check_runtime_environment,
            crate::interfaces::commands::setup_commands::check_ffmpeg_status,
            crate::interfaces::commands::setup_commands::check_runtime_readiness,
            crate::interfaces::commands::setup_commands::check_models_status,
            crate::interfaces::commands::setup_commands::get_environment_status,
            crate::interfaces::commands::setup_commands::is_setup_complete_fast,
            crate::interfaces::commands::setup_commands::is_setup_complete,
            crate::interfaces::commands::setup_commands::mark_setup_complete,
            crate::interfaces::commands::setup_commands::reset_setup,
            crate::interfaces::commands::performance_commands::get_performance_config,
            crate::interfaces::commands::performance_commands::update_performance_config,
        ]
    };
}

pub(crate) use app_invoke_handler;
