name: Build

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows-artifacts:
    uses: ./.github/workflows/windows-artifacts.yml
    with:
      run_checks: true
      installer_artifact_name: vocrify-windows-installer
      portable_artifact_name: vocrify-windows-portable
      tauri_target: x86_64-pc-windows-msvc
    secrets: inherit
